[default]

ssh_remote_password = ""
ssh_privkey_file = "~/.ssh/id_rsa.pub"
ssh_pubkey_file = "~/.ssh/id_rsa.pub"

[dev]

ssh_remote_password = ""
ssh_privkey_file = "~/.ssh/id_rsa.pub"
ssh_pubkey_file = "~/.ssh/id_rsa.pub"

[prod]

ssh_remote_password = ""
ssh_privkey_file = "~/.ssh/id_rsa.pub"
ssh_pubkey_file = "~/.ssh/id_rsa.pub"
