[default]

ssh_remote_host = ""
ssh_remote_user = ""
ssh_remote_ssh_port = 22
ssh_remote_cwd = ""

ssh_local_dest_path = ""

[dev]

ssh_remote_host = ""
ssh_remote_user = ""
ssh_remote_ssh_port = 22
ssh_remote_cwd = ""

ssh_local_dest_path = ""

[prod]

ssh_remote_host = ""
ssh_remote_user = ""
ssh_remote_ssh_port = 22
ssh_remote_cwd = ""

ssh_local_dest_path = ""
